# Generated by Django 3.2.25 on 2024-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cane_crush', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packsize',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
