# Generated by Django 3.2.25 on 2024-07-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cane_crush', '0005_orderitem_packsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pack_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pack_sizes', to='cane_crush.packsize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pack_sizes', to='cane_crush.product')),
            ],
            options={
                'unique_together': {('product', 'pack_size')},
            },
        ),
    ]
