# Generated by Django 3.2.25 on 2024-07-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cane_crush', '0006_productpacksize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
